# Generated by Django 6.0.3 on 2026-03-26 22:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("sis", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_average",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("overall_grade", models.CharField(blank=True, max_length=5)),
                ("class_rank", models.IntegerField(blank=True, null=True)),
                ("teacher_comment", models.TextField(blank=True)),
                ("principal_comment", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="report_cards/"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="sis.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "db_table": "report_cards",
                "ordering": ["-term", "student"],
            },
        ),
        migrations.CreateModel(
            name="SubjectGrade",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("grade", models.CharField(max_length=5)),
                ("teacher_comment", models.TextField(blank=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grades_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_grades",
                        to="reports.reportcard",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="academics.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "subject_grades",
                "ordering": ["report_card", "subject"],
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transcript_data", models.JSONField(default=dict)),
                (
                    "cumulative_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="transcripts/"),
                ),
                ("is_official", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcripts_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="sis.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "transcripts",
                "ordering": ["-academic_year", "student"],
            },
        ),
        migrations.AddIndex(
            model_name="reportcard",
            index=models.Index(
                fields=["tenant", "student"], name="report_card_tenant__80c7c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportcard",
            index=models.Index(
                fields=["tenant", "term"], name="report_card_tenant__7ca546_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportcard",
            index=models.Index(fields=["status"], name="report_card_status_fba963_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("tenant", "student", "term")},
        ),
        migrations.AddIndex(
            model_name="subjectgrade",
            index=models.Index(
                fields=["tenant", "report_card"], name="subject_gra_tenant__d7bfdc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectgrade",
            unique_together={("tenant", "report_card", "subject")},
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["tenant", "student"], name="transcripts_tenant__13d66b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["verification_code"], name="transcripts_verific_8f64be_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transcript",
            unique_together={("tenant", "student", "academic_year")},
        ),
    ]
