# Generated by Django 6.0.3 on 2026-03-26 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_as_teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="academics.class",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.grade",
            ),
        ),
        migrations.AddField(
            model_name="gradingscale",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="promotionrule",
            name="from_grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_rules_from",
                to="academics.grade",
            ),
        ),
        migrations.AddField(
            model_name="promotionrule",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="promotionrule",
            name="to_grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_rules_to",
                to="academics.grade",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_assignments",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="class_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="academics.classsubject",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(
                fields=["tenant", "status"], name="academic_ye_tenant__8c64a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(
                fields=["tenant", "is_current"], name="academic_ye_tenant__01dad3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicyear",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["tenant", "level"], name="grades_tenant__1b77d2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["tenant", "grade"], name="classes_tenant__88f2fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["is_active"], name="classes_is_acti_7c0b49_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("tenant", "grade", "name")},
        ),
        migrations.AddIndex(
            model_name="gradingscale",
            index=models.Index(
                fields=["tenant", "is_default"], name="grading_sca_tenant__12b9d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gradingscale",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="promotionrule",
            index=models.Index(
                fields=["tenant", "from_grade"], name="promotion_r_tenant__0cac4c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promotionrule",
            unique_together={("tenant", "from_grade", "to_grade")},
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["tenant", "is_active"], name="subjects_tenant__b033bf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["tenant", "class_assigned"],
                name="class_subje_tenant__55e166_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["tenant", "academic_year"],
                name="class_subje_tenant__80336a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("tenant", "class_assigned", "subject", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(
                fields=["tenant", "teacher"], name="teacher_ass_tenant__afdb9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(
                fields=["tenant", "class_subject"],
                name="teacher_ass_tenant__d5c5b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(
                fields=["is_active"], name="teacher_ass_is_acti_47a595_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherassignment",
            unique_together={("tenant", "teacher", "class_subject")},
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(
                fields=["tenant", "academic_year"], name="terms_tenant__e89f3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(fields=["status"], name="terms_status_8a6322_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together={("tenant", "academic_year", "term_number")},
        ),
    ]
