# Generated by Django 6.0.3 on 2026-03-26 22:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="School/Institution name", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Kenya", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("pro", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("trial", "Trial"),
                            ("inactive", "Inactive"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("subscription_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                ("timezone", models.CharField(default="Africa/Nairobi", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("features_enabled", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
                    models.Index(fields=["status"], name="tenants_status_80d9b6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year_start_month",
                    models.IntegerField(
                        default=1, help_text="Month when academic year starts (1-12)"
                    ),
                ),
                (
                    "academic_year_end_month",
                    models.IntegerField(
                        default=12, help_text="Month when academic year ends (1-12)"
                    ),
                ),
                (
                    "terms_per_year",
                    models.IntegerField(
                        default=3, help_text="Number of terms/semesters per year"
                    ),
                ),
                (
                    "grading_system",
                    models.JSONField(
                        default=dict,
                        help_text="Grading scale configuration (e.g., A=90-100, B=80-89)",
                    ),
                ),
                (
                    "pass_mark",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "attendance_tracking_mode",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("per_period", "Per Period"),
                            ("both", "Both"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("late_threshold_minutes", models.IntegerField(default=15)),
                (
                    "absence_alert_threshold",
                    models.IntegerField(
                        default=3,
                        help_text="Number of consecutive absences before alert",
                    ),
                ),
                (
                    "fee_payment_deadline_day",
                    models.IntegerField(
                        default=5, help_text="Day of month for fee payment deadline"
                    ),
                ),
                (
                    "late_payment_penalty_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("allow_partial_payments", models.BooleanField(default=True)),
                ("sms_notifications_enabled", models.BooleanField(default=True)),
                ("email_notifications_enabled", models.BooleanField(default=True)),
                ("whatsapp_notifications_enabled", models.BooleanField(default=False)),
                (
                    "notification_templates",
                    models.JSONField(
                        default=dict, help_text="Custom notification message templates"
                    ),
                ),
                (
                    "report_card_template",
                    models.CharField(
                        default="standard",
                        help_text="Report card template to use",
                        max_length=50,
                    ),
                ),
                ("include_teacher_comments", models.BooleanField(default=True)),
                ("include_principal_comments", models.BooleanField(default=True)),
                (
                    "custom_settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional custom settings"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_configs",
            },
        ),
        migrations.CreateModel(
            name="TenantDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_domains",
                "unique_together": {("tenant", "is_primary")},
            },
        ),
    ]
