# Generated by Django 6.0.3 on 2026-03-26 22:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("sis", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("period", "Period")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "period_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("period_name", models.CharField(blank=True, max_length=100)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False,
                        help_text="Once finalized, attendance cannot be changed",
                    ),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="academics.class",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_sessions_marked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_sessions",
                "ordering": ["-date", "class_assigned"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                            ("sick", "Sick"),
                            ("leave", "On Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "minutes_late",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("excuse_note", models.TextField(blank=True)),
                ("parent_notified", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="sis.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="attendance.attendancesession",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_records",
                "ordering": ["session", "student"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_sessions", models.IntegerField(default=0)),
                ("present_count", models.IntegerField(default=0)),
                ("absent_count", models.IntegerField(default=0)),
                ("late_count", models.IntegerField(default=0)),
                ("excused_count", models.IntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("consecutive_absences", models.IntegerField(default=0)),
                ("last_absence_date", models.DateField(blank=True, null=True)),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to="sis.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_summaries",
                "ordering": ["student", "-term"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceAlert",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("consecutive_absence", "Consecutive Absences"),
                            ("chronic_lateness", "Chronic Lateness"),
                            ("low_attendance_rate", "Low Attendance Rate"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "metric_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="e.g., number of consecutive absences or attendance percentage",
                        max_digits=5,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("parent_notified", models.BooleanField(default=False)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_attendance_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_alerts",
                        to="sis.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "student"],
                        name="attendance__tenant__1074d1_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_resolved"],
                        name="attendance__tenant__f4c282_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="attendance__severit_0eb070_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["tenant", "date"], name="attendance__tenant__66a71b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["tenant", "class_assigned", "date"],
                name="attendance__tenant__cfd7df_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesession",
            unique_together={
                ("tenant", "class_assigned", "date", "session_type", "period_number")
            },
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["tenant", "student"], name="attendance__tenant__09d512_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["tenant", "session"], name="attendance__tenant__228296_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["status"], name="attendance__status_5b1243_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("tenant", "session", "student")},
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["tenant", "student"], name="attendance__tenant__296610_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["tenant", "term"], name="attendance__tenant__f2125a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesummary",
            unique_together={("tenant", "student", "term")},
        ),
    ]
